/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextField;
import beans.Agence;
import test.Client;
import test.ServiceLocator;

/**
 *
 * @author Lakhassane
 */
public class AjoutAgenceGUI extends JFrame {

    /**
     * Creates new form AjoutAgenceGUI
     */
    public AjoutAgenceGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nomAgenceField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        adresseAgenceField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        creerAgenceButton = new javax.swing.JButton();
        creerEtNewAgenceButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome To Yet Another Bank");

        jLabel2.setText("Nom agence");

        adresseAgenceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresseAgenceFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Adresse");

        creerAgenceButton.setText("Créer");
        creerAgenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerAgenceButtonActionPerformed(evt);
            }
        });

        creerEtNewAgenceButton.setText("Retour");
        creerEtNewAgenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerEtNewAgenceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(creerAgenceButton)
                        .addGap(40, 40, 40)
                        .addComponent(creerEtNewAgenceButton))
                    .addComponent(nomAgenceField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adresseAgenceField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomAgenceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresseAgenceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creerAgenceButton)
                    .addComponent(creerEtNewAgenceButton))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adresseAgenceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresseAgenceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresseAgenceFieldActionPerformed

    private void creerAgenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerAgenceButtonActionPerformed
            /* We get the fields content */
//            Client.oos.writeObject("ajoutAgence");
//            Client.oos.flush();
            
            String nomAgence = nomAgenceField.getText();
            String adresseAgence = adresseAgenceField.getText();

            Agence agence = new Agence();
            agence.setNomag(nomAgence);
            agence.setAdresseag(adresseAgence);
            
            ServiceLocator.params[0] = agence;
            
            Object ob = ServiceLocator.getService("ajoutService", -1, "");

            /* We write the object in the output stream to send via the network */
//            Client.oos.writeObject(agence);
//            Client.oos.flush();
            
            /* Reset fields content */
            nomAgenceField.setText("");
            adresseAgenceField.setText("");
    }//GEN-LAST:event_creerAgenceButtonActionPerformed

    private void creerEtNewAgenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerEtNewAgenceButtonActionPerformed
        this.setVisible(false);
        new YABGUI().setVisible(true);        
    }//GEN-LAST:event_creerEtNewAgenceButtonActionPerformed
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AjoutAgenceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AjoutAgenceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AjoutAgenceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AjoutAgenceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AjoutAgenceGUI().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresseAgenceField;
    private javax.swing.JButton creerAgenceButton;
    private javax.swing.JButton creerEtNewAgenceButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomAgenceField;
    // End of variables declaration//GEN-END:variables


    /* GETTERS & SETTERS */
    public JTextField getAdresseAgenceField() {
        return adresseAgenceField;
    }
    public void setAdresseAgenceField(JTextField adresseAgenceField) {
        this.adresseAgenceField = adresseAgenceField;
    }
    public JButton getCreerAgenceButton() {
        return creerAgenceButton;
    }
    public void setCreerAgenceButton(JButton creerAgenceButton) {
        this.creerAgenceButton = creerAgenceButton;
    }
    public JButton getCreerEtNewAgenceButton() {
        return creerEtNewAgenceButton;
    }
    public void setCreerEtNewAgenceButton(JButton creerEtNewAgenceButton) {
        this.creerEtNewAgenceButton = creerEtNewAgenceButton;
    }
    public JTextField getNomAgenceField() {
        return nomAgenceField;
    }
    public void setNomAgenceField(JTextField nomAgenceField) {
        this.nomAgenceField = nomAgenceField;
    }
    /* END OF GETTERS & SETTERS */
}
