/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import test.Client;
import beans.Compte;
import beans.Customer;
import beans.Operation;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import test.ServiceLocator;

/**
 *
 * @author pacheikh
 */
public class AjoutCompteGUI extends javax.swing.JFrame {

    /**
     * Creates new form AjoutCompteGUI
     */
    public AjoutCompteGUI() {
        
        ArrayList<Customer> listeCustomer = (ArrayList<Customer>) ServiceLocator.getService("clientService", -1, "");
            
        String[] nomCustomer = new String[listeCustomer.size()];
        for ( int i = 0; i < listeCustomer.size(); i++ ) {
            nomCustomer[i] = listeCustomer.get(i).getNomCli();
        }

        clientComboBox = new JComboBox(nomCustomer);

        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numCompteField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        libelleCompteField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        soldeCompteField = new javax.swing.JTextField();
        creerCompteButton = new javax.swing.JButton();
        retourCreerCompteButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        clientComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("  Yet Another Bank");

        jLabel2.setText("Numéro du compte");

        jLabel3.setText("Libelle du compte");

        libelleCompteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libelleCompteFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Solde de départ (FCFA)");

        creerCompteButton.setText("Créer");
        creerCompteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerCompteButtonActionPerformed(evt);
            }
        });

        retourCreerCompteButton.setText("Retour");
        retourCreerCompteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourCreerCompteButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("client");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(creerCompteButton)
                .addGap(35, 35, 35)
                .addComponent(retourCreerCompteButton)
                .addContainerGap(325, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numCompteField)
                            .addComponent(libelleCompteField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soldeCompteField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(116, 116, 116))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numCompteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(clientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(libelleCompteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soldeCompteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creerCompteButton)
                    .addComponent(retourCreerCompteButton))
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numCompteField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        libelleCompteField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        soldeCompteField = new javax.swing.JTextField();
        creerCompteButton = new javax.swing.JButton();
        retourCreerCompteButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
//        clientComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome To Yet Another Bank");

        jLabel2.setText("Numéro du compte");

        jLabel3.setText("Libelle du compte");

        libelleCompteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libelleCompteFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Solde de départ (FCFA)");

        creerCompteButton.setText("Créer");
        creerCompteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerCompteButtonActionPerformed(evt);
            }
        });

        retourCreerCompteButton.setText("Retour");
        retourCreerCompteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourCreerCompteButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("client");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(creerCompteButton)
                .addGap(35, 35, 35)
                .addComponent(retourCreerCompteButton)))
                .addContainerGap(131, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2)
                .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(numCompteField)
                .addComponent(libelleCompteField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4)
                .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(clientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(soldeCompteField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(numCompteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5)
                .addComponent(clientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(libelleCompteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(soldeCompteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(creerCompteButton)
                .addComponent(retourCreerCompteButton))
                .addGap(90, 90, 90)));

        pack();
    }
    private void libelleCompteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libelleCompteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libelleCompteFieldActionPerformed

    private void retourCreerCompteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourCreerCompteButtonActionPerformed
        this.setVisible(false);
        YABGUI yabGui = new YABGUI();
        yabGui.setVisible(true);
    }//GEN-LAST:event_retourCreerCompteButtonActionPerformed

    private void creerCompteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerCompteButtonActionPerformed
//            Client.oos.writeObject("ajoutCompte");
//            Client.oos.flush();

            int numCompte = Integer.parseInt(numCompteField.getText());
            String libelleCompte = libelleCompteField.getText();
            float soldeCompte = Float.parseFloat(soldeCompteField.getText());
            int numClient = clientComboBox.getSelectedIndex() + 1;

            Compte compte = new Compte();
            compte.setNumcpt(numCompte);
            compte.setLibellecpt(libelleCompte);
            compte.setSoldecpt(soldeCompte);
            compte.setSenscpt("CR");
            compte.setNumcli(numClient);
            
            /* We write the object in the output stream to send via the network */
//            Client.oos.writeObject(compte);
//            Client.oos.flush();

            Date actuelle = new Date();
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
            
            Operation operation = new Operation();
            operation.setLibelleop("Ouverture compte");
            operation.setSensop("CR");
            operation.setDateop(dateFormat.format(actuelle));
            operation.setNumcpt(compte.getNumcpt());
            
            ServiceLocator.params[0] = compte;
            ServiceLocator.params[1] = operation;
            
            Object ob = ServiceLocator.getService("ajoutService", -1, "");

//            Client.oos.writeObject(operation);
//            Client.oos.flush();

            /* reset field contents */
            numCompteField.setText("");
            libelleCompteField.setText("");
            soldeCompteField.setText("");
        
    }//GEN-LAST:event_creerCompteButtonActionPerformed
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AjoutCompteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AjoutCompteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AjoutCompteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AjoutCompteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AjoutCompteGUI().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox clientComboBox;
    private javax.swing.JButton creerCompteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField libelleCompteField;
    private javax.swing.JTextField numCompteField;
    private javax.swing.JButton retourCreerCompteButton;
    private javax.swing.JTextField soldeCompteField;
    // End of variables declaration//GEN-END:variables
}
